# SITE CONFIGURATION
title: Ali Marques # your site title
author: Ali Marques # You :P
description: > # Meta description of Homepage
  Data Science
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://alimarques.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Ali Marques
  links:
    - https://www.linkedin.com/in/ali-marques
    - https://github.com/alimarques

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Sobre', link: '/sobre'}
  - {name: 'Contato', link: '/contato'}

tagline: >
  Dados, Tecnologia e ideias

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ali.mrques@gmail.com # email for form submission

github_username: alimarques # replace with your_github_username or comment to remove link from footer

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
